### ISSUE TITLE
Is it possible to add square brackets while setting version number in CHANGELOG.md for releases

### ISSUE THREAD

**Issue by Oran** [f3ath/cider#25]
Currently adds the version number without the square brackets
Github actions that read changes from change log supports version to be in brackets as shown in the image below
I know this is not an issue, but it would be great if it supports it.

![image](https://user-images.githubusercontent.com/42975732/126073290-7ea70a49-fc07-4e73-91f6-07ed31137efb.png)

**Comment by f3ath** [comment]
I'm not quite sure what you mean. Cider adds versions with a link to the diff whenever you provide the [tag and diff links in the config](https://github.com/f3ath/cider#configure). When a version link is added, the release H2 line will have the square brackets around the version and in the bottom of the file there will be the link itself.

Example of the version entry:
```
## [0.0.5] - 2020-09-09
### Added
- Setting version explicitly
- Ability to retain pre-release part of the version
```

and the corresponding link:
```
[0.0.5]: https://github.com/f3ath/cider/compare/0.0.4...0.0.5
```

**Comment by Oran** [comment]
@f3ath I understood, but do I have to manually change the `diff` link in `pubspec.yaml` for every version release?

**Comment by f3ath** [comment]
No, you do not. The diff link in `pubspec.yaml` is a template ([example](https://github.com/f3ath/cider/blob/6ea3599fedae3f417816ac5891cbb7d0d4ee9bed/pubspec.yaml#L32-L35))
```
cider:
  link_template:
    tag: 'https://github.com/f3ath/cider/releases/tag/%tag%' # initial release link template
    diff: 'https://github.com/f3ath/cider/compare/%from%...%to%' # subsequent releases link template
```
    
Cider will substitute `%tag%`, `%from%`,  and `%to%` with the corresponding version(s) for each release.
